version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: assecor-postgres
    environment:
      POSTGRES_DB: assecor_assessment
      POSTGRES_USER: assecor_user
      POSTGRES_PASSWORD: assecor_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U assecor_user -d assecor_assessment"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data: